apiVersion: v1
kind: Service
metadata:
  name: svc-http-echo
spec:
  selector:
    app: svc-http-echo
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5678
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
