apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-prometheus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: obs-prometheus
  template:
    metadata:
      labels:
        app: obs-prometheus
    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 9090
