apiVersion: apps/v1
kind: Deployment
metadata:
  name: util-dnsmasq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: util-dnsmasq
  template:
    metadata:
      labels:
        app: util-dnsmasq
    spec:
      containers:
      - name: dnsmasq
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 53
          protocol: UDP
