apiVersion: v1
kind: Service
metadata:
  name: util-dnsmasq
spec:
  selector:
    app: util-dnsmasq
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
  type: {{ .Values.service.type }}
